# =====================================
# CONFIGURACAO DO BANCO DE DADOS ORACLE
# =====================================
spring.datasource.url=jdbc:oracle:thin:@//oracle.fiap.com.br:1521/orcl
spring.datasource.username=rm559258
spring.datasource.password=170904
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=120000
spring.datasource.hikari.connection-timeout=20000

# =====================================
# CONFIGURA��O DO JPA / HIBERNATE
# =====================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
# =====================================
# JWT CONFIGURATION
# =====================================
app.jwtSecret=my-super-secret-key-that-is-at-least-32-characters-long-for-hs512
app.jwtExpirationInMs=86400000

# =====================================
# RABBITMQ CONFIGURATION
# =====================================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/
spring.rabbitmq.dynamic=true
spring.rabbitmq.listener.simple.auto-startup=true
spring.rabbitmq.listener.direct.auto-startup=true
app.rabbitmq.enabled=true

# =====================================
# FEIGN CONFIGURATION
# =====================================
feign.session-service.url=http://localhost:8081

# =====================================
# SERVER CONFIGURATION
# =====================================
server.port=8081
spring.application.name=libras-api

# =====================================
# LOGGING
# =====================================
logging.level.root=INFO
logging.level.com.librasja=DEBUG
logging.level.org.springframework.security=DEBUG